### PR TITLE
Added UserProfile UI screen

### PR DESCRIPTION
**Pull request by SiyingLi425**
Added UI interface "UserProfile.js" for other user's profile

### CODE REVIEW

**Comment by vuhieuphong** [comment]
Reviewed your commit and found no issue. Approved

**Comment by vuhieuphong** [comment]
Can you change the title Siying? It is not descriptive

**Comment by SiyingLi425** [comment]
Sorry, that was a mistake. It has been changed to the proper name.

**Comment by vuhieuphong** [comment]
Name change is now proper. Approved and merging to main.

**Pull request merged**
